print("My name is:")
print("Tornike")
print("l am 11 years old")
print("l am interested for:")
print("10 years")
print("l want to become profesional programer")
print("it is my dream")
print("l have small family:")
print("Dad, Mom and me")
print("we live in Tbilisi")
print("in varketili")
print("l like footbal")
print("my favourite footballer is Ronaldo")
print("because he won 5 champions legue")
print("and euro 2016 too")